export { default as Header } from "./Header/Header"
export { default as WhatGPT3 } from "./WhatGPT3/WhatGPT3"
export { default as Features } from "./Features/Features"
export { default as Possibility } from "./Possibility/Possibility"
export { default as Register } from "./Register/Register"
export { default as Blog } from "./Blog/Blog"
export { default as Footer } from "./Footer/Footer"
